// Generated by scripts/build-worker-contract-bundle.js. Do not edit.
export type Modality = "text" | "document" | "image" | "video" | "audio" | "music" | "automation";
export type PrivacyClass = "public" | "internal" | "restricted";
export type JobState = "queued" | "running" | "succeeded" | "failed" | "cancelling" | "cancelled";
export type ErrorCode = "VALIDATION_ERROR" | "AUTHENTICATION_REQUIRED" | "AUTHORIZATION_DENIED" | "POLICY_DENIED" | "NOT_FOUND" | "CONFLICT" | "DEPENDENCY_FAILURE" | "PROVIDER_FAILURE" | "INTEGRITY_VIOLATION" | "TIMEOUT" | "CANCELLED" | "INTERNAL_ERROR";
export interface Capability { id: string; modality: Modality; operations: string[]; privacy_classes: PrivacyClass[]; available: boolean; models: string[]; limits: { max_concurrency: number; max_input_bytes: number; timeout_seconds: number } }
export interface Capabilities { contract_version: 'l7.worker.capabilities/1.0'; worker_id: string; worker_version: string; generated_at: string; capabilities: Capability[] }
export interface JobRequest { contract_version?: 'l7.worker.job-request/1.0'; request_id?: string; capability: string; input: Record<string, unknown>; privacy_class: PrivacyClass; deadline: string; metadata?: Record<string, unknown> }
export interface Artifact { sha256: string; bytes: number; media_type: string; producer: string; model: string; model_version?: string | null; license_id: string; prompt_hash: string | null; created_at: string; delivery_url?: string }
export interface Job { contract_version: 'l7.worker.job/1.0'; job_id: string; request_id: string; tenant_id: string; capability: string; state: JobState; created_at: string; updated_at: string; progress: number; result?: unknown; artifacts: Artifact[]; error: { code: ErrorCode; message: string } | null }
export interface ClientOptions { fetch?: typeof globalThis.fetch; credentials?: RequestCredentials; headers?: Record<string, string> }
export class L7ApiError extends Error { status: number; code: ErrorCode | string; details: unknown; }
export class L7Client { constructor(baseUrl: string, options?: ClientOptions); capabilities(): Promise<Capabilities>; listJobs(): Promise<Job[]>; submitJob(request: JobRequest): Promise<Job>; getJob(jobId: string): Promise<Job>; cancelJob(jobId: string): Promise<Job>; artifactUrl(sha256: string): string; }
